// Code generated by "stringer -type=EventType"; DO NOT EDIT.

package mahjong

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventTypeGet - -1]
	_ = x[EventTypeTsumoGiri-0]
	_ = x[EventTypeDiscard-1]
	_ = x[EventTypeChi-2]
	_ = x[EventTypePon-3]
	_ = x[EventTypeDaiMinKan-4]
	_ = x[EventTypeShouMinKan-5]
	_ = x[EventTypeAnKan-6]
	_ = x[EventTypeRiichi-7]
	_ = x[EventTypeRon-8]
	_ = x[EventTypeTsumo-9]
	_ = x[EventTypeNewIndicator-10]
	_ = x[EventTypeChanKan-11]
	_ = x[EventTypeRyuuKyoku-12]
}

const _EventType_name = "EventTypeGetEventTypeTsumoGiriEventTypeDiscardEventTypeChiEventTypePonEventTypeDaiMinKanEventTypeShouMinKanEventTypeAnKanEventTypeRiichiEventTypeRonEventTypeTsumoEventTypeNewIndicatorEventTypeChanKanEventTypeRyuuKyoku"

var _EventType_index = [...]uint8{0, 12, 30, 46, 58, 70, 88, 107, 121, 136, 148, 162, 183, 199, 217}

func (i EventType) String() string {
	i -= -1
	if i < 0 || i >= EventType(len(_EventType_index)-1) {
		return "EventType(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
