// Code generated by "stringer -type=TileClass"; DO NOT EDIT.

package mahjong

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TileClassDummy - -1]
	_ = x[Man1-0]
	_ = x[Man2-1]
	_ = x[Man3-2]
	_ = x[Man4-3]
	_ = x[Man5-4]
	_ = x[Man6-5]
	_ = x[Man7-6]
	_ = x[Man8-7]
	_ = x[Man9-8]
	_ = x[Pin1-9]
	_ = x[Pin2-10]
	_ = x[Pin3-11]
	_ = x[Pin4-12]
	_ = x[Pin5-13]
	_ = x[Pin6-14]
	_ = x[Pin7-15]
	_ = x[Pin8-16]
	_ = x[Pin9-17]
	_ = x[Sou1-18]
	_ = x[Sou2-19]
	_ = x[Sou3-20]
	_ = x[Sou4-21]
	_ = x[Sou5-22]
	_ = x[Sou6-23]
	_ = x[Sou7-24]
	_ = x[Sou8-25]
	_ = x[Sou9-26]
	_ = x[Ton-27]
	_ = x[Nan-28]
	_ = x[Shaa-29]
	_ = x[Pei-30]
	_ = x[Haku-31]
	_ = x[Hatsu-32]
	_ = x[Chun-33]
	_ = x[RedMan5-34]
	_ = x[RedPin5-35]
	_ = x[RedSou5-36]
}

const _TileClass_name = "TileClassDummyMan1Man2Man3Man4Man5Man6Man7Man8Man9Pin1Pin2Pin3Pin4Pin5Pin6Pin7Pin8Pin9Sou1Sou2Sou3Sou4Sou5Sou6Sou7Sou8Sou9TonNanShaaPeiHakuHatsuChunRedMan5RedPin5RedSou5"

var _TileClass_index = [...]uint8{0, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58, 62, 66, 70, 74, 78, 82, 86, 90, 94, 98, 102, 106, 110, 114, 118, 122, 125, 128, 132, 135, 139, 144, 148, 155, 162, 169}

func (i TileClass) String() string {
	i -= -1
	if i < 0 || i >= TileClass(len(_TileClass_index)-1) {
		return "TileClass(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _TileClass_name[_TileClass_index[i]:_TileClass_index[i+1]]
}
