// Code generated by "stringer -type=Wind"; DO NOT EDIT.

package mahjong

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WindDummy - -1]
	_ = x[East-0]
	_ = x[South-1]
	_ = x[West-2]
	_ = x[North-3]
}

const _Wind_name = "WindDummyEastSouthWestNorth"

var _Wind_index = [...]uint8{0, 9, 13, 18, 22, 27}

func (i Wind) String() string {
	i -= -1
	if i < 0 || i >= Wind(len(_Wind_index)-1) {
		return "Wind(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _Wind_name[_Wind_index[i]:_Wind_index[i+1]]
}
