// Code generated by "stringer -type=RyuuKyokuReason"; DO NOT EDIT.

package mahjong

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RyuuKyokuNormal-0]
	_ = x[RyuuKyokuKyuShuKyuHai-1]
	_ = x[RyuuKyokuShuChaRiichi-2]
	_ = x[RyuuKyokuSuuKaiKan-3]
	_ = x[RyuuKyokuSuufonRenda-4]
	_ = x[RyuuKyokuSanChaHou-5]
}

const _RyuuKyokuReason_name = "RyuuKyokuNormalRyuuKyokuKyuShuKyuHaiRyuuKyokuShuChaRiichiRyuuKyokuSuuKaiKanRyuuKyokuSuufonRendaRyuuKyokuSanChaHou"

var _RyuuKyokuReason_index = [...]uint8{0, 15, 36, 57, 75, 95, 113}

func (i RyuuKyokuReason) String() string {
	if i < 0 || i >= RyuuKyokuReason(len(_RyuuKyokuReason_index)-1) {
		return "RyuuKyokuReason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RyuuKyokuReason_name[_RyuuKyokuReason_index[i]:_RyuuKyokuReason_index[i+1]]
}
